### ISSUE TITLE
simplivre-demo-style-classicthesis.tex does not compile

### ISSUE THREAD

**Issue by tfrank1971** [Jinwen-XU/minimalist#4]
I tried to compile the example file 'simplivre-demo-style-classicthesis.tex', but without success. It stops with the following message: 
```[8].../install/tex/luatex/luaotfload/fontloader-basics-gen.lua:156: bad argumen
t #2 to 'find_file' (invalid option '08;tex gyre pagella').
<to be read again> 
edef 
l.120 \blinddocument
                  
? 
```
All requested fonts are installed, includind TeX Gyre Pagella. I use latest MiKTeX 24.4 with all updates on Windows 11. Thanks in advance for your help.

**Comment by Jinwen-XU** [comment]
Thank you for pointing this out. When I try to recompile my previous (unchanged) file with LuaLaTeX, I also see the same error. Since it worked well half a year ago, I suspect that some packages' update somehow introduces new conflicts. It might take me some time to figure out what happened exactly, please be patient.

**Comment by Jinwen-XU** [comment]
So it turns out that this is actually an issue with `microtype` already dealt with here: https://github.com/schlcht/microtype/issues/35. To make it work as of now, you could download the `dev` version of `microtype` (https://github.com/schlcht/microtype/tree/dev), compile the `microtype.ins`, and copy every generated file to your working folder. The document should now compile without error.

If you encounter any further issue, feel free to reopen this Issue or open a new one.

**Comment by tfrank1971** [comment]
I see. Thank you very much.
